import type { Metadata } from "next";
import "./globals.css";
import Script from 'next/script';
import Header from './component/headers';
import MainTop from './component/main-top';
import TopSearch from './component/top-search';
import Footer from './component/footers';
import CopyRight from './component/copy-right';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        {/* Mobile Metas */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Site Metas */}
        <title>ThewayShop - Ecommerce Bootstrap 4 HTML Template</title>
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {/* Site Icons */}
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <link rel="apple-touch-icon" href="images/apple-touch-icon.png" />
        {/* Bootstrap CSS */}
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        {/* Site CSS */}
        <link rel="stylesheet" href="/css/style.css" />
        {/* Responsive CSS */}
        <link rel="stylesheet" href="/css/responsive.css" />
        {/* Custom CSS */}
        <link rel="stylesheet" href="/css/custom.css" />
      </head>

      <body>
        <MainTop />
        <Header />
        <TopSearch />

        {children}

        <Footer />
        <CopyRight />

        <Script src="/js/jquery-3.2.1.min.js" strategy="beforeInteractive"></Script>
        <Script src="/js/popper.min.js"></Script>
        <Script src="/js/bootstrap.min.js"></Script>
        <Script src="/js/jquery.superslides.min.js" strategy="beforeInteractive"></Script>
        <Script src="/js/bootstrap-select.js" strategy="beforeInteractive"></Script>
        <Script src="/js/inewsticker.js" strategy="beforeInteractive"></Script>
        <Script src="/js/bootsnav.js" strategy="beforeInteractive"></Script>
        <Script src="/js/images-loded.min.js" strategy="beforeInteractive"></Script>
        <Script src="/js/isotope.min.js" strategy="beforeInteractive"></Script>
        <Script src="/js/owl.carousel.min.js" strategy="beforeInteractive"></Script>
        <Script src="/js/baguetteBox.min.js" strategy="beforeInteractive"></Script>
        <Script src="/js/form-validator.min.js" strategy="beforeInteractive"></Script>
        <Script src="/js/contact-form-Script.js"></Script>
        <Script src="/js/custom.js"></Script>
      </body>
    </html>
  );
}
